### ISSUE TITLE
Implement "hide matches" option

### ISSUE THREAD

**Issue by svendcs** [judoassistant/judoassistant#105]
The current "disable draw" option should be replaced with a "hide matches option". The underlying logic should be changed accordingly. This would allow for better planning and web display.

## TODO

* [ ] - Hide matches in web UI where relevant
* [x] - Hide matches when populating tatami
* [x] - Add to json encoder
